
import Dominio.*;
import Data.*;
import controller.Controladora;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.Year;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Christian D
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    Controladora control;
    
    public test() {
        initComponents();
        control = new Controladora(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        JD1 = new com.toedter.calendar.JDateChooser();
        JD2 = new com.toedter.calendar.JDateChooser();
        JY1 = new com.toedter.calendar.JYearChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(JD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        getContentPane().add(JD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        getContentPane().add(JY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, -1));

        tabla = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 1200, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:    
         Data dato = new Data();
         /*
        Lugar l = new Lugar(1,"Hola","hola");
        dato.InsertarLugar(l);
        
        Hotel h = new Hotel(1,"Sun and beach","*****","Basico, Solo desayuno","Calle 9","Edificio Tropical","el Verano",1);
       
       dato.InsertarHotel(h); 
       h = new Hotel(1,"Sun","*****","Basico, Solo desayuno","Calle 14","Edificio Tropical","el Verano",1);
       dato.ModificarHotel(h);
       
       Personal p = new Personal("25329474","Carlita","Reyes","Calle 5","Edificio 9","Urb la urb",'F',convertJavaDateToSqlDate(JD1.getDate()),convertJavaDateToSqlDate(JD2.getDate()),"Supervisor","Bachiller",1,0,1,"25329674");
       
       dato.InsertarPersonal(p);
       p = new Personal ("25329674","ramon","Ramones","Calle 6","Edificio 10","urb la estancia",'M',convertJavaDateToSqlDate(JD1.getDate()),convertJavaDateToSqlDate(JD2.getDate()),"Gerente","Cualquiercosa",1,1,1,"25329474");
       dato.InsertarPersonal(p);
       p = new Personal("25329674","Carlos","Reyes","Calle 5","Edificio 9","Urb la urb",'F',convertJavaDateToSqlDate(JD1.getDate()),convertJavaDateToSqlDate(JD2.getDate()),"Administrador","Bachiller",1,1,1,"25329474");
       dato.ModificarPersonal(p);
       
       p = new Personal("25329675","Carlos1","Reyes","Calle 5","Edificio 9","Urb la urb",'F',convertJavaDateToSqlDate(JD1.getDate()),convertJavaDateToSqlDate(JD2.getDate()),"Gerente","Bachiller",1,1,1,"25329474");
       dato.InsertarPersonal(p);
       p = new Personal("25329676","Carlos2","Reyes","Calle 5","Edificio 9","Urb la urb",'F',convertJavaDateToSqlDate(JD1.getDate()),convertJavaDateToSqlDate(JD2.getDate()),"Encargado","Bachiller",1,1,1,"25329474");
       dato.InsertarPersonal(p);
       p = new Personal("25329677","Carlos3","Reyes","Calle 5","Edificio 9","Urb la urb",'F',convertJavaDateToSqlDate(JD1.getDate()),convertJavaDateToSqlDate(JD2.getDate()),"Piscinero","Bachiller",1,1,1,"25329474");
       dato.InsertarPersonal(p);
         p = new Personal("25329678","Carlos3","Reyes","Calle 5","Edificio 9","Urb la urb",'F',convertJavaDateToSqlDate(JD1.getDate()),convertJavaDateToSqlDate(JD2.getDate()),"Piscinero","Bachiller",1,1,1,"25329474");
       dato.InsertarPersonal(p);
         p = new Personal("25329679","Carlos3","Reyes","Calle 5","Edificio 9","Urb la urb",'F',convertJavaDateToSqlDate(JD1.getDate()),convertJavaDateToSqlDate(JD2.getDate()),"Piscinero","Bachiller",1,1,1,"25329474");
       dato.InsertarPersonal(p);
       
       Compañia c = new Compañia("j-1231241212","Sony","Calle 4","Urb plomero","Edif El edificio","0426-2335908","Proveedor",1);
       dato.InsertarCompañia(c);
       c = new Compañia("j-1231241243","Microsoft","Calle 4","Urb plomero","Edif El edificio","0426-2335908","Limpieza",1);
       dato.InsertarCompañia(c);
       c = new Compañia("j-1231241243","Microsoft","Calle 10","Urb Scorpio","Edif El edificio","0426-2335908","Limpieza",1);
       dato.ModificarCompañia(c);
       TrabajoLimpieza tl = new TrabajoLimpieza(1,"Limpiar Ventanas");
       dato.InsertarTrabajoLimpieza(tl);
       tl = new TrabajoLimpieza(1,"Limpiar Pisos");
       dato.ModificarTrabajoLimpieza(tl);
       TrabajoCompañia tc = new TrabajoCompañia(1,"j-1231241212",2500);
       dato.InsertarTrabajoCompañia(tc);
       FacturaLimpieza fl = new FacturaLimpieza(1,convertJavaDateToSqlDate(JD1.getDate()),convertJavaDateToSqlDate(JD1.getDate()),convertJavaDateToSqlDate(JD1.getDate()),"Este es una prueba",1,"j-1231241212");
       dato.InsertarFacturaTrabajosLimpieza(fl);
       fl = new FacturaLimpieza(1,convertJavaDateToSqlDate(JD1.getDate()),convertJavaDateToSqlDate(JD1.getDate()),convertJavaDateToSqlDate(JD1.getDate()),"Si modifico",1,"j-1231241243");
       dato.ModificarFacturaTrabajosLimpieza(fl);
       ProductoImplemento pi = new ProductoImplemento(1,0,5,4,convertJavaDateToSqlDate(JD1.getDate()),1);
       dato.InsertarProducto(pi);
       pi = new ProductoImplemento(1,1,6,4,convertJavaDateToSqlDate(JD2.getDate()),1);
       dato.ModificarProducto(pi);
       Ajuste a = new Ajuste(convertJavaDateToSqlDate(JD1.getDate()),2,"NoSE",1);
       dato.InsertarAjuste(a);
       a = new Ajuste(convertJavaDateToSqlDate(JD1.getDate()),5,"SiSe",1);
       dato.ModificarAjuste(a);
       OrdenCompra oc = new OrdenCompra(1,convertJavaDateToSqlDate(JD1.getDate()),5,convertJavaDateToSqlDate(JD1.getDate()),"j-1231241212",1);
       dato.InsertarOrdenCompra(oc);
       oc = new OrdenCompra(1,convertJavaDateToSqlDate(JD2.getDate()),10,convertJavaDateToSqlDate(JD2.getDate()),"j-1231241243",1);
       dato.ModificarOrdenCompra(oc);
       Cliente cl = new Cliente (1,JY1.getYear(),"25329675","Roberto","Escolar","02121111111","04261111111","02125097453",convertJavaDateToSqlDate(JD1.getDate()),"Español",'M',"Profesor","El PAPAUPA",1,1,1,"Calle Loma","Edificio Loma","Urbanizacion Loma");
       dato.InsertarCliente(cl);
       cl = new Cliente (1,JY1.getYear(),"25329675","Roberta","Escolar","022222222","04261111111","02125097453",convertJavaDateToSqlDate(JD1.getDate()),"Tailandes",'F',"Ex Profesor","EL PAPAUPA",1,1,1,"Calle Lomo","Edificio Lomo","Urbanizacion Lomo");
       dato.ModificarCliente(cl);
      
       
       //dato.Eliminar(h.getCodigo(),"Hotel","Codigo");
      
       Acompañante ac = new Acompañante("25322222","Hifumi","Takimoto",convertJavaDateToSqlDate(JD1.getDate()),"Waifu");
       dato.InsertarAcompañante(ac);
       ac = new Acompañante("25322222","Akiyama","mio",convertJavaDateToSqlDate(JD2.getDate()),"Waifu");
       dato.ModificarAcompañante(ac);
       
       Experiencia exp = new Experiencia("Oracle","Supervisor",convertJavaDateToSqlDate(JD2.getDate()),convertJavaDateToSqlDate(JD2.getDate()),"25329675");
       dato.InsertarExperiencia(exp);
       
       Lenguaje len = new Lenguaje("Japones","25329676");
       dato.InsertarLenguaje(len);
       
       Amonestacion amo = new Amonestacion(0,convertJavaDateToSqlDate(JD2.getDate()),"NIIDEEA1","22324963");
       dato.InsertarAmonestacion(amo);
       amo = new Amonestacion(0,convertJavaDateToSqlDate(JD2.getDate()),"NIIDEEA1","20432853");
       dato.InsertarAmonestacion(amo);
       amo = new Amonestacion(0,convertJavaDateToSqlDate(JD2.getDate()),"NIIDEEA1","21372961");
       dato.InsertarAmonestacion(amo);
       
      
      amo = new Amonestacion(0,convertJavaDateToSqlDate(JD2.getDate()),"NIIDEEA2","25329677");
       dato.InsertarAmonestacion(amo);
       
       amo = new Amonestacion(0,convertJavaDateToSqlDate(JD2.getDate()),"NIIDEEA3","25329677");
       dato.InsertarAmonestacion(amo);
       
       amo = new Amonestacion(0,convertJavaDateToSqlDate(JD2.getDate()),"NIIDEEA4","25329678");
       dato.InsertarAmonestacion(amo);
       
       amo = new Amonestacion(0,convertJavaDateToSqlDate(JD2.getDate()),"NIIDEEA5","25329678");
       dato.InsertarAmonestacion(amo);
       
       amo = new Amonestacion(0,convertJavaDateToSqlDate(JD2.getDate()),"NIIDEEA6","25329678");
       dato.InsertarAmonestacion(amo);
       
      control.GenerarCondicionConsulta("Cliente","Nombre", "Apellido", "CI", "Jose", "Oliveira", "25871114");
      control.GenerarCondicionDelete("Cliente","Nombre", "Apellido","","Julio","Rico","");
      String condicion =control.GenerarCondicionConsulta("Personal_7", "", "Edificio", "Urbanizacion", "","Edificio", "El");
      DefaultTableModel modelo = control.ConsultarGeneral(condicion);
      System.out.println(modelo.getDataVector());
      tabla.setModel(modelo);
      System.out.println(tabla.getColumnCount());*/
     // control.GenerarReporte1(1, "La Luciernaga");
    //  dato.EliminarGeneral(control.GenerarCondicionDelete("Detalle_Factura_7","Costo", "", "","120000", "",""));
    
    /*control.PagoFacturaLimpieza(1,"Cheque", convertJavaDateToSqlDate(new java.util.Date()));
    tabla.setModel(control.RevisarPagoFactura("1"));*/
    /*control.PagoOrdenCompra(1,convertJavaDateToSqlDate(new java.util.Date()));
    tabla.setModel(control.RevisarPagoOren("1"));*/
    //tabla.setModel(control.ConsultarGeneral(control.GenerarCondicionConsulta("Cliente_7","","Nacionalidad","","","Venezolano","")));
     //System.out.println(control.ConsultaPrimaria("Codigo","Lugar_7","Descripcion","Lara"));
   
     //control.ComprobarMesInventario("5");
    //tabla.setModel(dato.ConsultaHotel(control.GenerarCondicionSelect("Urbanizacion", "","","","","")));
    //tabla.setModel(dato.ConsultaCompañiaLimpieza(control.GenerarCondicionSelect("", "","","","","")));
     //tabla.setModel(dato.ConsultaProveedor(control.GenerarCondicionSelect("", "","","","","")));
     //tabla.setModel(dato.ConsultaFacturaLimpieza(control.GenerarCondicionSelect("", "","","","","")));
     //tabla.setModel(dato.ConsultaProducto(control.GenerarCondicionSelect("", "","","","","")));
     //tabla.setModel(dato.ConsultaOrdenCompra(control.GenerarCondicionSelect("", "","","","","")));
     //tabla.setModel(dato.ConsultaTrabajoCompañia(control.GenerarCondicionSelect("", "","","","","")));
     
     //tabla.setModel(dato.ConsultaPersonal(control.GenerarCondicionSelect("","","","","","")));
    // tabla.setModel(dato.ConsultaAjuste(control.GenerarCondicionSelect("","","","","",""),"Sun and Beach"));
    //tabla.setModel(dato.ConsultaAcompañante(control.GenerarCondicionSelect("Nombre","Apellido","Fecha_nacimiento","","","")));
    //tabla.setModel(dato.ConsultaExperiencia(control.GenerarCondicionSelect("Compañia","Cargo","","","",""),"20896348"));
    tabla.setModel(dato.ConsultaCliente(control.GenerarCondicionSelect("", "", "", "", "", "")));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }
  public static java.sql.Date convertJavaDateToSqlDate(java.util.Date date){
    if(date != null) {
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        return sqlDate;
    }
    return null;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JD1;
    private com.toedter.calendar.JDateChooser JD2;
    private com.toedter.calendar.JYearChooser JY1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
